### PR TITLE
Added functionality to use any custom views for content

### PR DESCRIPTION
**Pull request by miketsprague**
Instead of being restricted to only images.

### CODE REVIEW

**Comment by MatthewYork** [comment]
As it has been a major feature request, I definitely want to pull this in! Is there any way you could whip up a quick demo using your new methods?

**Comment by miketsprague** [comment]
Sure!  Do you want an example project or just a code snippet?
It's really as simple as:

```
    UIView *content = [[[NSBundle mainBundle] loadNibNamed:@"TutorialView_1" owner:self options:nil] objectAtIndex:0];
    MYIntroductionPanel *panel = [[MYIntroductionPanel alloc] initWithContentView:content];
    panel.Title = @"TODO: Fill me in!";
    panel.Description = @"Description field!";
```

You can make views any way shape or form you want, as well as adding as many subviews as you want and it should behave the same way.  If the view is larger than the width of the tutorial view, then it'll be sized down to fit.

Big caveat though: If you use a nib with AutoLayout it seems to break the user interaction functionality.  Strange.

**Comment by MatthewYork** [comment]
I've gotten your snippet working with a test nib in the iOS 6 phone sim, and everything looks great. I'm going to put it through its paces a bit more (iOS 7, iPad) and then, if everything looks good, I will merge it in. This will be a great addition!

**Comment by miketsprague** [comment]
Awesome!

**Comment by MatthewYork** [comment]
Thanks for all your hard work work, Mike. It looks to be a great addition!

**Comment by MatthewYork** [comment]
Mike, 

I expanded on your idea and went ahead to make a new controller entirely. This one supports full-screen custom panels and much more. Hope you like it!

https://github.com/MatthewYork/MYBlurIntroductionView

**Comment by miketsprague** [comment]
Looks awesome!  Glad I could provide some help!

**Pull request merged**
